/**
 * AI facade.
 *
 * Flow, per the architecture requirement:
 *   request → bounded context → provider → schema validation → result → user edits → save
 *
 * This module never touches the database. Callers build the context, call in,
 * and decide what to persist after the user has reviewed it. Usage is recorded
 * by the caller through `recordAiUsage`.
 */

import { hasOpenAi, env } from '../../env.js';
import type { BrandContext, ContentRequest } from './context.js';
import { findForbidden, platformRule } from './context.js';
import type { CampaignFacts } from './facts.js';
import { openAiAnalysis, openAiCopy, openAiHashtags, openAiReviewReply } from './openai.js';
import { templateAnalysis, templateCopy, templateHashtags } from './template.js';
import { generatedCopySchema, type AiResult, type Analysis, type GeneratedCopy } from './schemas.js';
import { aiHealth, recordProviderFailure, recordProviderSuccess } from './health.js';

const FALLBACK_NOTICE =
  'Generated by the built-in template engine — no OPENAI_API_KEY is configured, so no language model was called.';

function timed<T>(started: number, data: T, provider: 'openai' | 'template', notice?: string): AiResult<T> {
  return {
    data,
    provider,
    model: provider === 'openai' ? env.OPENAI_MODEL : 'template-v1',
    latencyMs: Date.now() - started,
    isFallback: provider === 'template',
    ...(notice ? { notice } : {}),
  };
}

/**
 * Strip any brand-forbidden word from generated copy. The model is told not to
 * use them, but the brand's ban is enforced here rather than trusted.
 */
function scrub(copy: GeneratedCopy, forbidden: string[]): { copy: GeneratedCopy; removed: string[] } {
  if (forbidden.length === 0) return { copy, removed: [] };

  const removed = new Set<string>();
  const clean = (value: string): string => {
    let output = value;
    for (const word of forbidden) {
      const trimmed = word.trim();
      if (trimmed.length === 0) continue;
      const pattern = new RegExp(trimmed.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
      if (pattern.test(output)) {
        removed.add(trimmed);
        output = output.replace(pattern, '').replace(/\s{2,}/g, ' ').trim();
      }
    }
    return output;
  };

  return {
    copy: {
      ...copy,
      headline: clean(copy.headline),
      caption: clean(copy.caption),
      primaryText: clean(copy.primaryText),
      shortText: clean(copy.shortText),
      longText: clean(copy.longText),
      slogan: clean(copy.slogan),
      cta: clean(copy.cta),
      hashtags: copy.hashtags.filter((tag) => findForbidden(tag, forbidden).length === 0),
      keywords: copy.keywords.filter((word) => findForbidden(word, forbidden).length === 0),
    },
    removed: [...removed],
  };
}

export async function generateCopy(
  brand: BrandContext,
  request: ContentRequest,
): Promise<AiResult<GeneratedCopy>> {
  const started = Date.now();

  if (hasOpenAi) {
    try {
      const raw = await openAiCopy(brand, request);
      recordProviderSuccess();
      const { copy, removed } = scrub(raw, brand.forbiddenWords);
      const notice = removed.length > 0 ? `Removed brand-forbidden wording: ${removed.join(', ')}.` : undefined;
      return timed(started, generatedCopySchema.parse(copy), 'openai', notice);
    } catch (error) {
      // A provider failure must not fail the user's request — degrade instead.
      // Recorded as well as logged: a degradation nobody can see is the failure
      // mode this whole health module exists to make visible.
      recordProviderFailure('generateCopy', error);
      console.warn('[ai] OpenAI copy generation failed, using template engine:', (error as Error).message);
    }
  }

  const { copy } = scrub(templateCopy(brand, request), brand.forbiddenWords);
  return timed(started, generatedCopySchema.parse(copy), 'template', FALLBACK_NOTICE);
}

export async function generateHashtags(
  brand: BrandContext,
  request: ContentRequest,
  limit?: number,
): Promise<AiResult<string[]>> {
  const started = Date.now();
  const max = limit ?? platformRule(request.platform).hashtags ?? 10;

  if (max === 0) return timed(started, [], 'template', 'This platform does not use hashtags.');

  if (hasOpenAi) {
    try {
      const tags = await openAiHashtags(brand, request, max);
      recordProviderSuccess();
      const filtered = tags.filter((tag) => findForbidden(tag, brand.forbiddenWords).length === 0);
      if (filtered.length > 0) return timed(started, filtered, 'openai');
    } catch (error) {
      recordProviderFailure('generateHashtags', error);
      console.warn('[ai] OpenAI hashtag generation failed, using template engine:', (error as Error).message);
    }
  }

  const tags = templateHashtags(brand, request, max).filter(
    (tag) => findForbidden(tag, brand.forbiddenWords).length === 0,
  );
  return timed(started, tags, 'template', FALLBACK_NOTICE);
}

export async function analyzeCampaigns(facts: CampaignFacts): Promise<AiResult<Analysis>> {
  const started = Date.now();

  if (hasOpenAi) {
    try {
      const analysis = await openAiAnalysis(facts);
      recordProviderSuccess();
      return timed(started, analysis, 'openai');
    } catch (error) {
      recordProviderFailure('analyzeCampaigns', error);
      console.warn('[ai] OpenAI analysis failed, using rule-based analyst:', (error as Error).message);
    }
  }

  return timed(
    started,
    templateAnalysis(facts),
    'template',
    'Produced by the built-in rule-based analyst. Every figure quoted is measured, not estimated.',
  );
}

/**
 * A suggested public reply to a review.
 *
 * Degrades to a template like every other generator here, so a deployment with
 * no OPENAI_API_KEY still produces something an operator can edit rather than an
 * error. Either way it is a *suggestion*: nothing in this module can publish,
 * and the route that can will not accept a suggestion that a human has not
 * approved.
 */
export async function generateReviewReply(
  brand: BrandContext,
  review: { rating: number; comment: string | null; category: string; reviewerName?: string | null; language: string },
): Promise<AiResult<{ reply: string }>> {
  const started = Date.now();

  if (hasOpenAi) {
    try {
      const reply = await openAiReviewReply({ brand, ...review });
      recordProviderSuccess();
      const { removed, text } = scrubText(reply, brand.forbiddenWords);
      const notice = removed.length > 0 ? `Removed brand-forbidden wording: ${removed.join(', ')}.` : undefined;
      return timed(started, { reply: text }, 'openai', notice);
    } catch (error) {
      recordProviderFailure('generateReviewReply', error);
      console.warn('[ai] OpenAI review reply failed, using template:', (error as Error).message);
    }
  }

  const { text } = scrubText(templateReply(brand, review), brand.forbiddenWords);
  return timed(started, { reply: text }, 'template', FALLBACK_NOTICE);
}

/** Strips brand-forbidden words from a free-text string. */
function scrubText(text: string, forbidden: string[]): { text: string; removed: string[] } {
  const removed = findForbidden(text, forbidden);
  let output = text;
  for (const word of removed) {
    output = output.replace(new RegExp(word.replace(/[.*+?^$()|[\]\\]/g, '\\$&'), 'gi'), '').replace(/\s{2,}/g, ' ');
  }
  return { text: output.trim(), removed };
}

/**
 * The no-API-key reply.
 *
 * Deliberately plain and slightly generic: it is a starting point an operator
 * edits, and a template that tried to sound specific would put invented detail
 * about a visit nobody witnessed into a public answer.
 */
function templateReply(
  brand: BrandContext,
  review: { rating: number; comment: string | null; language: string },
): string {
  const arabic = review.language === 'AR';
  const name = brand.businessName;

  if (review.rating >= 4) {
    return arabic
      ? `شكراً جزيلاً على تقييمك ومشاركتك تجربتك مع ${name}. يسعدنا أن الزيارة نالت إعجابك، ونتطلع لاستقبالك مرة أخرى.`
      : `Thank you for taking the time to share this. We are glad the visit lived up to expectations, and the team at ${name} looks forward to welcoming you back.`;
  }

  if (review.rating <= 2) {
    return arabic
      ? `نأسف لأن تجربتك مع ${name} لم تكن كما ينبغي، ونشكرك على إخبارنا. نود الاستماع إلى التفاصيل، فيرجى التواصل معنا مباشرة حتى نتمكن من معالجة الأمر.`
      : `We are sorry this visit fell short of what ${name} aims for, and we appreciate you telling us. We would like to hear the details directly so we can look into it properly — please get in touch with us.`;
  }

  return arabic
    ? `شكراً على ملاحظاتك. نأخذ كل تعليق على محمل الجد في ${name}، ويسعدنا التواصل معك لمعرفة المزيد.`
    : `Thank you for the feedback. We take every comment seriously at ${name}, and we would welcome the chance to hear more.`;
}

/**
 * What the AI layer is doing right now.
 *
 * `provider` and `configured` still answer the old question — is a key set —
 * and every existing caller keeps working unchanged. `health` answers the one
 * the audit found nobody could answer: whether a configured key is *working*,
 * or whether generations are quietly falling back to templates anyway.
 */
export const aiStatus = () => {
  const health = aiHealth();
  return {
    provider: hasOpenAi ? 'openai' : 'template',
    model: hasOpenAi ? env.OPENAI_MODEL : 'template-v1',
    configured: hasOpenAi,
    /** The provider a request would actually be served by, given current health. */
    effectiveProvider: health.state === 'HEALTHY' || health.state === 'UNVERIFIED' ? 'openai' : 'template',
    health,
  };
};

export { aiHealth, probeProvider, resetProviderHealth } from './health.js';
export type { AiHealth, AiProviderState, ProviderProbe } from './health.js';
export type { GeneratedCopy, Analysis, AiResult };
export * from './context.js';
export * from './facts.js';
