/**
 * AI facade.
 *
 * Flow, per the architecture requirement:
 *   request → bounded context → provider → schema validation → result → user edits → save
 *
 * This module never touches the database. Callers build the context, call in,
 * and decide what to persist after the user has reviewed it. Usage is recorded
 * by the caller through `recordAiUsage`.
 */

import { hasOpenAi, env } from '../../env.js';
import type { BrandContext, ContentRequest } from './context.js';
import { findForbidden, platformRule } from './context.js';
import type { CampaignFacts } from './facts.js';
import { openAiAnalysis, openAiCopy, openAiHashtags } from './openai.js';
import { templateAnalysis, templateCopy, templateHashtags } from './template.js';
import { generatedCopySchema, type AiResult, type Analysis, type GeneratedCopy } from './schemas.js';

const FALLBACK_NOTICE =
  'Generated by the built-in template engine — no OPENAI_API_KEY is configured, so no language model was called.';

function timed<T>(started: number, data: T, provider: 'openai' | 'template', notice?: string): AiResult<T> {
  return {
    data,
    provider,
    model: provider === 'openai' ? env.OPENAI_MODEL : 'template-v1',
    latencyMs: Date.now() - started,
    isFallback: provider === 'template',
    ...(notice ? { notice } : {}),
  };
}

/**
 * Strip any brand-forbidden word from generated copy. The model is told not to
 * use them, but the brand's ban is enforced here rather than trusted.
 */
function scrub(copy: GeneratedCopy, forbidden: string[]): { copy: GeneratedCopy; removed: string[] } {
  if (forbidden.length === 0) return { copy, removed: [] };

  const removed = new Set<string>();
  const clean = (value: string): string => {
    let output = value;
    for (const word of forbidden) {
      const trimmed = word.trim();
      if (trimmed.length === 0) continue;
      const pattern = new RegExp(trimmed.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
      if (pattern.test(output)) {
        removed.add(trimmed);
        output = output.replace(pattern, '').replace(/\s{2,}/g, ' ').trim();
      }
    }
    return output;
  };

  return {
    copy: {
      ...copy,
      headline: clean(copy.headline),
      caption: clean(copy.caption),
      primaryText: clean(copy.primaryText),
      shortText: clean(copy.shortText),
      longText: clean(copy.longText),
      slogan: clean(copy.slogan),
      cta: clean(copy.cta),
      hashtags: copy.hashtags.filter((tag) => findForbidden(tag, forbidden).length === 0),
      keywords: copy.keywords.filter((word) => findForbidden(word, forbidden).length === 0),
    },
    removed: [...removed],
  };
}

export async function generateCopy(
  brand: BrandContext,
  request: ContentRequest,
): Promise<AiResult<GeneratedCopy>> {
  const started = Date.now();

  if (hasOpenAi) {
    try {
      const raw = await openAiCopy(brand, request);
      const { copy, removed } = scrub(raw, brand.forbiddenWords);
      const notice = removed.length > 0 ? `Removed brand-forbidden wording: ${removed.join(', ')}.` : undefined;
      return timed(started, generatedCopySchema.parse(copy), 'openai', notice);
    } catch (error) {
      // A provider failure must not fail the user's request — degrade instead.
      console.warn('[ai] OpenAI copy generation failed, using template engine:', (error as Error).message);
    }
  }

  const { copy } = scrub(templateCopy(brand, request), brand.forbiddenWords);
  return timed(started, generatedCopySchema.parse(copy), 'template', FALLBACK_NOTICE);
}

export async function generateHashtags(
  brand: BrandContext,
  request: ContentRequest,
  limit?: number,
): Promise<AiResult<string[]>> {
  const started = Date.now();
  const max = limit ?? platformRule(request.platform).hashtags ?? 10;

  if (max === 0) return timed(started, [], 'template', 'This platform does not use hashtags.');

  if (hasOpenAi) {
    try {
      const tags = await openAiHashtags(brand, request, max);
      const filtered = tags.filter((tag) => findForbidden(tag, brand.forbiddenWords).length === 0);
      if (filtered.length > 0) return timed(started, filtered, 'openai');
    } catch (error) {
      console.warn('[ai] OpenAI hashtag generation failed, using template engine:', (error as Error).message);
    }
  }

  const tags = templateHashtags(brand, request, max).filter(
    (tag) => findForbidden(tag, brand.forbiddenWords).length === 0,
  );
  return timed(started, tags, 'template', FALLBACK_NOTICE);
}

export async function analyzeCampaigns(facts: CampaignFacts): Promise<AiResult<Analysis>> {
  const started = Date.now();

  if (hasOpenAi) {
    try {
      return timed(started, await openAiAnalysis(facts), 'openai');
    } catch (error) {
      console.warn('[ai] OpenAI analysis failed, using rule-based analyst:', (error as Error).message);
    }
  }

  return timed(
    started,
    templateAnalysis(facts),
    'template',
    'Produced by the built-in rule-based analyst. Every figure quoted is measured, not estimated.',
  );
}

export const aiStatus = () => ({
  provider: hasOpenAi ? 'openai' : 'template',
  model: hasOpenAi ? env.OPENAI_MODEL : 'template-v1',
  configured: hasOpenAi,
});

export type { GeneratedCopy, Analysis, AiResult };
export * from './context.js';
export * from './facts.js';
